apiVersion: apps/v1
kind: Deployment
metadata:
  name: innersource-portal-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      innersource-portal-app
      version: 2.0.0
  template:
    metadata:
      labels:
        app: innersource-portal-app
        version: 2.0.0
    spec:
      containers:
        - name: innersource-portal-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "PORT"
              value: "90"