apiVersion: apps/v1
kind: Deployment
metadata:
  name: innersource-portal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innersource-portal-app
      version: 2.0.0
  template:
    metadata:
      labels:
        app: innersource-portal-app
        version: 2.0.0
    spec:
      containers:
        - name: innersource-portal-app
          image: "swasthllc/innersource-portal-repo:main-latest"
          imagePullPolicy: Always
          env:
            - name: "PORT"
              value: "90"