apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: innersource-portal-app-ingress 
spec:
  rules:
  -  http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: innersource-portal-app-service 
            port: 
              number: 90