apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: innersource-portal-app-ingress 
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: innersource-portal-app-service 
          servicePort: http