apiVersion: v1
kind: Service
metadata:
  name: innersource-portal-app-service
  labels:
    app: innersource-portal-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 90
      targetPort: 9080
  selector:
    app: innersource-portal-app
    version: 2.0.0
